### PR TITLE
fix: fixed import uri when wsdl request is redirected

### LINKED ISSUE #351: Can't parse correct URI from `schemaLocation` in import when WSDL redirected to another location
# Steps to reproduce
I have WSDL URI like this: https://example.com/service.wso?WSDL
when making a request to it, it redirects to https://example.com/sub/folder/service.wso?WSDL

Till now it's fine and strong-soap will detect the WSDL and parse it, the issue happens when strong-soap tries to parse this import line:

`<xsd:import schemaLocation="Common.xsd">`

Then strong-soap will try to get this file from `https://example.com/Common.xsd` which will return 404 not found

# Expected result
The import request returns 404, as the WSDL URI has been redirected to https://example.com/sub/folder/service.wso?WSDL, so when parsing the imports it should resolve the `schemaLocation` to the correct WSDL location

# Additional information
I will send a PR to fix this issue, if you don't mind

### PR DESCRIPTION
**Pull request by asaid-0**
Signed-off-by: Elsaid Achraf <60660214+asaid-0@users.noreply.github.com>

### Description
Fixes #351 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by asaid-0** [comment]
@achrinza Can you please review this?

**Comment by achrinza** [comment]
Hi @asaid-0, thanks for the PR! I'll need some time to cross-check this against the spec, etc. to make sure it doesn't conflict. At a glance, the PR looks ok, just missing new tests to prevent future regression.

**Comment by asaid-0** [comment]
> At a glance, the PR looks ok, just missing new tests to prevent future regression.

Hi @achrinza I have added a test for this issue

**Review by achrinza — APPROVED** [review]

**Comment by achrinza** [comment]
Thanks for your contributions @asaid-0; Your changes have been merged :tada:

**Comment by asaid-0** [comment]
> Thanks for your contributions @asaid-0; Your changes have been merged 🎉

Thanks, @achrinza, is this going to be released as a patch soon?

**Pull request merged**
