### PR TITLE
chore: switch to httpntlm and fix flaky test

### PR DESCRIPTION
**Pull request by toddtarsi**
### Description

Switches httpntlm-maa to the supported thing.
Fixed the test suite by repairing the bad async bits in the prior test to the reporting test.

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [X] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by toddtarsi** [comment]
@raymondfeng @achrinza - Would one of you be able to look at this PR sometime this week? It deals with a couple Soc-2 issues around request and tough-cookie I think.

**Review by achrinza — APPROVED** [review]

**Comment by achrinza** [comment]
Thanks for the PR and test fixes! Your changes have been merged 🎉

**Comment by toddtarsi** [comment]
Yay! Thank you @achrinza !

**Comment by dhmlau** [comment]
`strong-soap@4.0.4` is just released.

**Comment by toddtarsi** [comment]
Woohoo! Thanks @dhmlau

**Comment by s100** [comment]
Part of #328 and #535.

**Pull request merged**
