### PR TITLE
feat: adding option to disable server pretty formatting

### PR DESCRIPTION
**Pull request by natanbcpc**
#### Related issues

- connect to #766 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
@natanbcpc, thanks for your PR. Your changes LGTM.

**Comment by natanbcpc** [comment]
@dhmlau sorry to bother, but do you have an estimate of when a new version will be released with this change?

**Comment by dhmlau** [comment]
@natanbcpc, actually I'm just about to start my publishing round for the month. Should be done within the next hour.

**Comment by dhmlau** [comment]
`strong-soap@4.1.0` is published that has your changes. Thanks.

**Pull request merged**
